// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: '1:992685844395:web:5b9a39c79f7f6d1f4554ee',
    messagingSenderId: '992685844395',
    projectId: 'spectrum-access-499918',
    authDomain: 'spectrum-access-499918.firebaseapp.com',
    storageBucket: 'spectrum-access-499918.firebasestorage.app',
    measurementId: 'G-0NN1TS6J3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: '1:992685844395:android:529958f0da7204c04554ee',
    messagingSenderId: '992685844395',
    projectId: 'spectrum-access-499918',
    storageBucket: 'spectrum-access-499918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'FIREBASE_API_KEY_REMOVED',
    appId: '1:992685844395:ios:65139c0cf127590a4554ee',
    messagingSenderId: '992685844395',
    projectId: 'spectrum-access-499918',
    storageBucket: 'spectrum-access-499918.firebasestorage.app',
    iosBundleId: 'cat.accessibilitat.sensoryAccess',
  );
}
